chain: "iotex"
interval: 1m
batchSize: 1000
database:
  uri: "root:kdfjjrU64fjK58H@tcp(localhost:13306)/witness?parseTime=true"
  driver: "mysql"
cashiers:
  - id: "iotex-to-ethereum"
    relayerURL: ":7000"
    cashierContractAddress: "io1gsr52ahqzklaf7flqar8r0269f2utkw9349qg8"
    validatorContractAddress: "0xd8165188ccc135b3a3b2a5d2bc3af9d94753d955"
    startBlockHeight: 9526978
    transferTableName: "iotex_transfers"
    tokenPairs:
      # WETH
      - token1: "io1qfvgvmk6lpxkpqwlzanqx4atyzs86ryqjnfuad"
        token2: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
      # WBTC
      - token1: "io1c7unwg8h8vph89xwqru4f7zfa4yy5002wxvlrm"
        token2: "0x2260fac5e5542a773aa44fbcfedf7c193bc2c599"
      # BUSD
      - token1: "io14nhfkywdfvl40evgsqnh43ev33q6he8yez8c8a"
        token2: "0x4Fabb145d64652a948d72533023f6E7A623C7C53"
      # UNI
      - token1: "io1ahh04jn2zkqlug6feh7rpq75a75p3rj42hp4ch"
        token2: "0x1f9840a85d5af5bf1d1762f925bdaddc4201f984"
      # PAXG
      - token1: "io19fsq8e9krrlng4ay5gyq6q5tqfym28yq9ly0fz"
        token2: "0x45804880De22913dAFE09f4980848ECE6EcbAf78"
      # CYC
      - token1: "io1f4acssp65t6s90egjkzpvrdsrjjyysnvxgqjrh"
        token2: "0x8861cfF2366C1128fd699B68304aD99a0764Ef9a"
      # MIST
      - token1: "io14xuv3gq2yzmcug9t0uwhate99djyux5zwdurtm"
        token2: "0x88ACDd2a6425c3FaAE4Bc9650Fd7E27e0Bebb7aB"
      # MCN
      - token1: "io18lsyxgygtesjggcj2nyqyqzgwxlxsysc9lgmg8"
        token2: "0xD227c3e4f3F8dE94180269eF9DC221a6efc1F4C4"
      # USDT
      - token1: "io1d77dcytfk5fsck089eg7669gfpqunrx35ue5ln"
        token2: "0xdAC17F958D2ee523a2206206994597C13D831ec7"
      # USDC
      - token1: "io18v4l9dfr74xyu320pz4zsmgrz9d07vnvy20yrh"
        token2: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
      # DAI
      - token1: "io1rjadsk4xdleuztwgf3vgrzrwav5urwumaakt0w"
        token2: "0x6b175474e89094c44da98b954eedeac495271d0f"
      # iMagic
      - token1: "io1cxfj43hs44nqhc6pkhycpezd7vdrpafgxnnzdt"
        token2: "0xb0Ed1F44833C6b2Afa39a6a85ff62C8ad96F5275"
      # CIOTX
      - token1: "io1nxetpma4de3wx6tqcgxdtj5wc64a24t64dc76s"
        token2: "0x9f90b457dea25ef802e38d470dda7343691d8fe1"
      # CCCS
      - token1: "io1daejpenv38639dw8xplp7c9zr4ff0c9p9kfx3g"
        token2: "0xf79deaBc1406a3AD07c70877fBaEb90777B77E68"
      # CTSI
      - token1: "io16ajfjch2hlm56vnhlwvs7g7aptnvx40ksyvrz5"
        token2: "0x30e68fACB9D4E04FEdc12A8Cc539639f90F40c63"
  - id: "iotex-to-heco"
    relayerURL: ":7002"
    cashierContractAddress: "io1s6m6j3cdj0j7hlgupx0pww7wscvkepdjfwgkra"
    validatorContractAddress: "0xDe9395d2f4940aA501f9a27B98592589D14Bb0f7"
    startBlockHeight: 2431000
    transferTableName: "iotex_to_heco_transfers"
    tokenPairs:
  - id: "iotex-to-polis"
    relayerURL: ":7005"
    cashierContractAddress: "io1aw89kuzrlyekzvwqyw3e82c880qaxwup5hv7ee"
    validatorContractAddress: "0xBa6DB98f32e66ad3eC20d79F062Eed50c6cb9F9f"
    startBlockHeight: 15670000
    transferTableName: "iotex_to_polis_transfers"
    tokenPairs:
      - token1: "io1nxetpma4de3wx6tqcgxdtj5wc64a24t64dc76s"
        token2: "0xe55AcA08126342eE1c70f218d26e553986687227"
      - token1: "io1d77dcytfk5fsck089eg7669gfpqunrx35ue5ln"
        token2: "0x56704Fb558527DD7FeE2CaBa541d87Bf2c8cc6Ea"
      - token1: "io18v4l9dfr74xyu320pz4zsmgrz9d07vnvy20yrh"
        token2: "0x673Be93F4862D1d1F1B0E5Db62Aa853156DFb932"
      - token1: "io1rjadsk4xdleuztwgf3vgrzrwav5urwumaakt0w"
        token2: "0x3bAe1e38F6e1E7E29C11cC735334cFd9f881EED7"
  - id: "iotex-to-bsc"
    relayerURL: ":7003"
    cashierContractAddress: "io1zjlng7je02kxyvjq4eavswp6uxvfvcnh2a0a3d"
    validatorContractAddress: "0x116404F86e97846110EA08cd52fC2882d4AD3123"
    startBlockHeight: 5177821
    transferTableName: "iotex_to_bsc_transfers"
    tokenPairs:
      - token1: "io1jlnvfzr8lhper2xla8gknmxsqhgajq5ravu4wr"
        token2: "0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c"
      - token1: "io1sj4uk2pjhesxxsd9qy52avwmgw4qzazfrypm04"
        token2: "0xe9e7cea3dedca5984780bafc599bd69add087d56"
      - token1: "io1f4acssp65t6s90egjkzpvrdsrjjyysnvxgqjrh"
        token2: "0x810ee35443639348adbbc467b33310d2ab43c168"
      - token1: "io1nxetpma4de3wx6tqcgxdtj5wc64a24t64dc76s"
        token2: "0x2aaF50869739e317AB80A57Bf87cAA35F5b60598"
      - token1: "io1gtyj2h272ghg8vtw5ydrhgzv95a0egre4zemtf"
        token2: "0x55d398326f99059ff775485246999027b3197955"
      - token1: "io1qde5ded9wg540tpv4dkwhrr5lsvva2ga3hf6ry"
        token2: "0x8ac76a51cc950d9822d68b83fe1ad97b32cd580d"
      - token1: "io1p00c9unkxz0zal2fglhguz3y3vnjd6xlx24h8m"
        token2: "0x7e544f2fEDDc69b1cB12555779c824CFe100ee34"
      - token1: "io19zrne65vymmq8v2exluesk5g33w6tlvskfj3c9"
        token2: "0x049Dd7532148826CdE956c7B45fec8c30b514052"
      - token1: "io1cx6cvg9dswfc83nzhl5qmdz3gdzda3khtt6asw"
        token2: "0xa0CB9c8e470EC591dd7f5De650af9468EE6f7d5A"
      # THC
      - token1: "io1kn9axz8g08qv8gafj6kkcatkky362ph5jntc9r"
        token2: "0x8Dfb1099C53f634BEcf3C98aE19eB1BAA1b37D43"
      # IoTexShiba
      - token1: "io1ld5l9sxecjzkftkn9tcudu6z5qmvjj2zfamvcw"
        token2: "0x52702a7301be185cc97bf3fe6d497a83e7772fde"
  - id: "iotex-to-matic"
    relayerURL: ":7004"
    cashierContractAddress: "io12s9f9hv4zsr7umy5hxt6g0k0xr4x6pxdp5w998"
    validatorContractAddress: "0xFBe9A4138AFDF1fA639a8c2818a0C4513fc4CE4B"
    startBlockHeight: 10000000
    transferTableName: "iotex_to_matic_transfers"
    tokenPairs:
      - token1: "io13envp44hps9j85ulfvs6r6k99wagaky60pzl2c"
        token2: "0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270"
      - token1: "io1v5m9d7zrs852xkdzdresqf3phwc5cchc5crylc"
        token2: "0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619"
      - token1: "io10u9dv0ys93nmr7smzyptpkhlhzylt4wtqzrvld"
        token2: "0x1BFD67037B42Cf73acF2047067bd4F2C47D9BfD6"
      - token1: "io1v25anp7t7nz954gdam2m27eqp4arr93jly4maa"
        token2: "0x8f3Cf7ad23Cd3CaDbD9735AFf958023239c6A063"
      - token1: "io18ndhcj88pwz5a5h68yhzz6r4q8vykwhugq45ns"
        token2: "0xc2132D05D31c914a87C6611C10748AEb04B58e8F"
      - token1: "io1cpx682vazuf4s4amjd7jlwejr5akc65plgmdru"
        token2: "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174"
      - token1: "io1990thrrc9cvxhjmsmx5pysznqs734h6uhxfxkq"
        token2: "0x0b3F868E0BE5597D5DB7fEB59E1CADBb0fdDa50a"
      - token1: "io1u346nz58mj5cjuj7ng3cn96upwam37v9axtju2"
        token2: "0x831753DD7087CaC61aB5644b308642cc1c33Dc13"
      - token1: "io14tw8gyn3p8v5fcmvh4c0w8797ryjrlrvnsr6zf"
        token2: "0xD6DF932A45C0f255f85145f286eA0b292B21C90B"
      - token1: "io1f4acssp65t6s90egjkzpvrdsrjjyysnvxgqjrh"
        token2: "0xcFb54a6D2dA14ABeCD231174FC5735B4436965D8"
      - token1: "io1nxetpma4de3wx6tqcgxdtj5wc64a24t64dc76s"
        token2: "0x300211Def2a644b036A9bdd3e58159bb2074d388"
      - token1: "io1g29kuat5d727cqcjv5ta8607ys9kdp5fx702ua"
        token2: "0xe04E81331bDcBfBF2D1342714812d546a55CB6DC"
