chain: "ethereum"
grpcPort: 9082
grpcProxyPort: 9083
interval: 1m
batchSize: 40
database:
  uri: "root:kdfjjrU64fjK58H@tcp(localhost:13306)/witness?parseTime=true"
  driver: "mysql"
cashiers:
  - id: "ethereum-to-iotex"
    relayerURL: ":7001"
    startBlockHeight: 18800000
    validatorContractAddress: "io10xr64as4krm5nufd5l2ddc43al6tl0smumkg7y"
    cashierContractAddress: "0xa0fd7430852361931b23a31f84374ba3314e1682"
    tokenSafeContractAddress: "0xc2e0f31d739cb3153ba5760a203b3bd7c27f0d7a"
    transferTableName: "ethereum_transfers"
    tokenPairs:
      # WETH
      - token2: "io1qfvgvmk6lpxkpqwlzanqx4atyzs86ryqjnfuad"
        token1: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
      # WBTC
      - token2: "io1c7unwg8h8vph89xwqru4f7zfa4yy5002wxvlrm"
        token1: "0x2260fac5e5542a773aa44fbcfedf7c193bc2c599"
      # BUSD
      - token2: "io14nhfkywdfvl40evgsqnh43ev33q6he8yez8c8a"
        token1: "0x4Fabb145d64652a948d72533023f6E7A623C7C53"
      # UNI
      - token2: "io1ahh04jn2zkqlug6feh7rpq75a75p3rj42hp4ch"
        token1: "0x1f9840a85d5af5bf1d1762f925bdaddc4201f984"
      # PAXG
      - token2: "io19fsq8e9krrlng4ay5gyq6q5tqfym28yq9ly0fz"
        token1: "0x45804880De22913dAFE09f4980848ECE6EcbAf78"
      # CYC
      - token2: "io1f4acssp65t6s90egjkzpvrdsrjjyysnvxgqjrh"
        token1: "0x8861cfF2366C1128fd699B68304aD99a0764Ef9a"
      # MIST
      - token2: "io14xuv3gq2yzmcug9t0uwhate99djyux5zwdurtm"
        token1: "0x88ACDd2a6425c3FaAE4Bc9650Fd7E27e0Bebb7aB"
      # MCN
      - token2: "io18lsyxgygtesjggcj2nyqyqzgwxlxsysc9lgmg8"
        token1: "0xD227c3e4f3F8dE94180269eF9DC221a6efc1F4C4"
      # USDT
      - token2: "io1d77dcytfk5fsck089eg7669gfpqunrx35ue5ln"
        token1: "0xdAC17F958D2ee523a2206206994597C13D831ec7"
      # USDC
      - token2: "io18v4l9dfr74xyu320pz4zsmgrz9d07vnvy20yrh"
        token1: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
      # DAI
      - token2: "io1rjadsk4xdleuztwgf3vgrzrwav5urwumaakt0w"
        token1: "0x6b175474e89094c44da98b954eedeac495271d0f"
      # iMagic
      - token2: "io1cxfj43hs44nqhc6pkhycpezd7vdrpafgxnnzdt"
        token1: "0xb0Ed1F44833C6b2Afa39a6a85ff62C8ad96F5275"
      # CIOTX
      - token2: "io1nxetpma4de3wx6tqcgxdtj5wc64a24t64dc76s"
        token1: "0x9f90b457dea25ef802e38d470dda7343691d8fe1"
      # CCCS
      - token2: "io1daejpenv38639dw8xplp7c9zr4ff0c9p9kfx3g"
        token1: "0xf79deaBc1406a3AD07c70877fBaEb90777B77E68"
      # CTSI
      - token2: "io16ajfjch2hlm56vnhlwvs7g7aptnvx40ksyvrz5"
        token1: "0x30e68fACB9D4E04FEdc12A8Cc539639f90F40c63"
      # ELA
      - token2: "io18l9s83sftn2t727wa2qh0ze7c5jm5ru58832se"
        token1: "0x77480e1E8441FAdf4D67dAb68249F08129d3dcA4"
      # CRU
      - token2: "io1mrm6dm4mudkau3sk9as0v9prysg5670vcx6rl8"
        token1: "0x9c3af6ffccac8a4ccb31a4b769b84a517c6c13b5"
