chain: "iotex-e"
interval: 1m
clientURL: "https://babel-api.mainnet.iotex.one"
grpcPort: 7001
grpcProxyPort: 8001
ethGasPriceLimit: 2000000000000
privateKey: ""
slackWebHook: "" 
validators:
  - address: "io10xr64as4krm5nufd5l2ddc43al6tl0smumkg7y"
    cashiers:
      - "0xa0fd7430852361931b23a31f84374ba3314e1682"
      - "0xf72CFb704d49aC7BB7FFa420AE5f084C671A29be"
      - "0x797f1465796fd89ea7135e76dbc7cdb136bba1ca"
database:
  uri: "root:kdfjjrU64fjK58H@tcp(database:3306)/relayer?parseTime=true"
  driver: "mysql"
transferTableName: "iotex_transfers"
witnessTableName: "iotex_witnesses"
bonus: "500000000000000000"
