chain: "ethereum"
interval: 2m
clientURL: ""
ethConfirmBlockNumber: 20
ethGasPriceLimit: 10000000000
grpcPort: 7000
grpcProxyPort: 8000
privateKey: ""
slackWebHook: "" 
validators:
  - address: "0xd8165188CCC135B3A3B2a5D2Bc3AF9D94753d955"
    cashiers:
      - "io1gsr52ahqzklaf7flqar8r0269f2utkw9349qg8"
database:
  uri: "root:kdfjjrU64fjK58H@tcp(database:3306)/relayer?parseTime=true"
  driver: "mysql"
transferTableName: "ethereum_transfers"
witnessTableName: "ethereum_witnesses"
