chain: "iotex"
grpcPort: 9280
grpcProxyPort: 9281
interval: 1m
batchSize: 1000
database:
  uri: "root:kdfjjrU64fjK58H@tcp(localhost:13306)/witness?parseTime=true"
  driver: "mysql"
cashiers:
  - id: "iotex-to-ethereum-payload"
    withPayload: true
    relayerURL: ":7200"
    cashierContractAddress: "0x4Aad62e13cBd5cD6F5BcEc649cc24f6185011fe1"
    validatorContractAddress: "0xE7eBA1CEA51EC9B3AcCC16728e3B8786560c59d5"
    startBlockHeight: 32739910
    transferTableName: "iotex_transfers"
    tokenPairs:
      # WETH
      - token1: "io1qfvgvmk6lpxkpqwlzanqx4atyzs86ryqjnfuad"
        token2: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
      # WBTC
      - token1: "io1c7unwg8h8vph89xwqru4f7zfa4yy5002wxvlrm"
        token2: "0x2260fac5e5542a773aa44fbcfedf7c193bc2c599"
      # BUSD
      - token1: "io14nhfkywdfvl40evgsqnh43ev33q6he8yez8c8a"
        token2: "0x4Fabb145d64652a948d72533023f6E7A623C7C53"
      # UNI
      - token1: "io1ahh04jn2zkqlug6feh7rpq75a75p3rj42hp4ch"
        token2: "0x1f9840a85d5af5bf1d1762f925bdaddc4201f984"
      # PAXG
      - token1: "io19fsq8e9krrlng4ay5gyq6q5tqfym28yq9ly0fz"
        token2: "0x45804880De22913dAFE09f4980848ECE6EcbAf78"
      # CYC
      - token1: "io1f4acssp65t6s90egjkzpvrdsrjjyysnvxgqjrh"
        token2: "0x8861cfF2366C1128fd699B68304aD99a0764Ef9a"
      # MIST
      - token1: "io14xuv3gq2yzmcug9t0uwhate99djyux5zwdurtm"
        token2: "0x88ACDd2a6425c3FaAE4Bc9650Fd7E27e0Bebb7aB"
      # MCN
      - token1: "io18lsyxgygtesjggcj2nyqyqzgwxlxsysc9lgmg8"
        token2: "0xD227c3e4f3F8dE94180269eF9DC221a6efc1F4C4"
      # USDT
      - token1: "io1d77dcytfk5fsck089eg7669gfpqunrx35ue5ln"
        token2: "0xdAC17F958D2ee523a2206206994597C13D831ec7"
      # USDC
      - token1: "io18v4l9dfr74xyu320pz4zsmgrz9d07vnvy20yrh"
        token2: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
      # DAI
      - token1: "io1rjadsk4xdleuztwgf3vgrzrwav5urwumaakt0w"
        token2: "0x6b175474e89094c44da98b954eedeac495271d0f"
      # iMagic
      - token1: "io1cxfj43hs44nqhc6pkhycpezd7vdrpafgxnnzdt"
        token2: "0xb0Ed1F44833C6b2Afa39a6a85ff62C8ad96F5275"
      # CIOTX
      - token1: "io1nxetpma4de3wx6tqcgxdtj5wc64a24t64dc76s"
        token2: "0x9f90b457dea25ef802e38d470dda7343691d8fe1"
      # CCCS
      - token1: "io1daejpenv38639dw8xplp7c9zr4ff0c9p9kfx3g"
        token2: "0xf79deaBc1406a3AD07c70877fBaEb90777B77E68"
      # CTSI
      - token1: "io16ajfjch2hlm56vnhlwvs7g7aptnvx40ksyvrz5"
        token2: "0x30e68fACB9D4E04FEdc12A8Cc539639f90F40c63"
      # ELA
      - token1: "io18l9s83sftn2t727wa2qh0ze7c5jm5ru58832se"
        token2: "0x77480e1E8441FAdf4D67dAb68249F08129d3dcA4"
      # CRU
      - token1: "io1mrm6dm4mudkau3sk9as0v9prysg5670vcx6rl8"
        token2: "0x9c3af6ffccac8a4ccb31a4b769b84a517c6c13b5"
      # ATOR
      - token1: "io1mypw5gnl79d8t6436zfg9psd40llndr2x9ntp6"
        token2: "0x6ed84215c7c4e94b0dc55c16e574d407586d2116"
      # MXC
      - token1: "io1t5cm7h7f2s0vxw2ft7p3yqdygycnx5hf03dxj7"
        token2: "0xC4fFC19CB3dfE37152d07a5444254930e9FF7127"
      # BZZ
      - token1: "io125ncge9vg39m4u67dl8vpa0gxwqmkdq86plm7e"
        token2: "0xDfF04A48baa71021e0221e9B26DD3C13cdC2FE7e"
      # STOS
      - token1: "io1dskaukl7ghuj6a3rflt7zkphdsxwyd3hhg43yx"
        token2: "0xf96c9ea3b23d7ba69c90d506ecb54a7e77958d50"
      # NOIA
      - token1: "io1ns80pjvwra4qv70yymm5xly56j5a8gkednnl8f"
        token2: "0xedf708dcf579d4c6ea7889ae255ba66ad2cf9757"
      # INJ
      - token1: "io1xk48emnzhra9kplcv0aqmgddtpzfjs0gpj6n5z"
        token2: "0x370f98048a45d04b57c6008b636ace4f6e8e1343"
      # USDa
      - token1: "0xeaa38983d3370e35fb42229f89e816e28035a74b"
        token2: "0xBB76063476A79F73624386795f4CcA855954C891"
  - id: "iotex-to-bsc-payload"
    withPayload: true
    relayerURL: ":7203"
    cashierContractAddress: "0xa016f866a606221E9C9E6ab3a942Bfc81F6074f4"
    validatorContractAddress: "0x95C6F6Af2c0Fa069768203FDa963d7626efC794a"
    startBlockHeight: 32739491
    transferTableName: "iotex_to_bsc_transfers"
    tokenPairs:
      # WBNB
      - token1: "io1jlnvfzr8lhper2xla8gknmxsqhgajq5ravu4wr"
        token2: "0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c"
      # BUSD
      - token1: "io1sj4uk2pjhesxxsd9qy52avwmgw4qzazfrypm04"
        token2: "0xe9e7cea3dedca5984780bafc599bd69add087d56"
      # CYC
      - token1: "io1f4acssp65t6s90egjkzpvrdsrjjyysnvxgqjrh"
        token2: "0x810ee35443639348adbbc467b33310d2ab43c168"
      # CIOTX
      - token1: "io1nxetpma4de3wx6tqcgxdtj5wc64a24t64dc76s"
        token2: "0x2aaF50869739e317AB80A57Bf87cAA35F5b60598"
      # BSC-USD
      - token1: "io1gtyj2h272ghg8vtw5ydrhgzv95a0egre4zemtf"
        token2: "0x55d398326f99059ff775485246999027b3197955"
      # USDC
      - token1: "io1qde5ded9wg540tpv4dkwhrr5lsvva2ga3hf6ry"
        token2: "0x8ac76a51cc950d9822d68b83fe1ad97b32cd580d"
      # CFOR
      - token1: "io1p00c9unkxz0zal2fglhguz3y3vnjd6xlx24h8m"
        token2: "0x7e544f2fEDDc69b1cB12555779c824CFe100ee34"
      # TEX
      - token1: "io19zrne65vymmq8v2exluesk5g33w6tlvskfj3c9"
        token2: "0x049Dd7532148826CdE956c7B45fec8c30b514052"
      # CbioShib
      - token1: "io1cx6cvg9dswfc83nzhl5qmdz3gdzda3khtt6asw"
        token2: "0xa0CB9c8e470EC591dd7f5De650af9468EE6f7d5A"
      # THC
      - token1: "io1kn9axz8g08qv8gafj6kkcatkky362ph5jntc9r"
        token2: "0x8Dfb1099C53f634BEcf3C98aE19eB1BAA1b37D43"
      # IoTexShiba
      - token1: "io1ld5l9sxecjzkftkn9tcudu6z5qmvjj2zfamvcw"
        token2: "0x52702a7301be185cc97bf3fe6d497a83e7772fde"
      # DRF
      - token1: "io1mm5eya89mz3dmp0lqtlfuydf67nrdhnwg92dy4"
        token2: "0x02dF5253Bc4EfC9F8f744133Ff99981b18Df0473"
  - id: "iotex-to-matic-payload"
    withPayload: true
    relayerURL: ":7204"
    cashierContractAddress: "0x8114746E4308a4d3Ff2a74B66414fF35657Fa0E2"
    previousCashierContractAddress: "0x124B468860ac994ef28D11643d16e88dd4F26085"
    validatorContractAddress: "0x87E2D48De6CC2029fFc1a915462e4Aa597890cd6"
    startBlockHeight: 32723537
    transferTableName: "iotex_to_matic_transfers"
    tokenPairs:
      # WMATIC
      - token1: "io13envp44hps9j85ulfvs6r6k99wagaky60pzl2c"
        token2: "0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270"
      # WETH
      - token1: "io1v5m9d7zrs852xkdzdresqf3phwc5cchc5crylc"
        token2: "0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619"
      # WBTC
      - token1: "io10u9dv0ys93nmr7smzyptpkhlhzylt4wtqzrvld"
        token2: "0x1BFD67037B42Cf73acF2047067bd4F2C47D9BfD6"
      # DAI
      - token1: "io1v25anp7t7nz954gdam2m27eqp4arr93jly4maa"
        token2: "0x8f3Cf7ad23Cd3CaDbD9735AFf958023239c6A063"
      # USDT
      - token1: "io18ndhcj88pwz5a5h68yhzz6r4q8vykwhugq45ns"
        token2: "0xc2132D05D31c914a87C6611C10748AEb04B58e8F"
      # USDC
      - token1: "io1cpx682vazuf4s4amjd7jlwejr5akc65plgmdru"
        token2: "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174"
      # SUSHI
      - token1: "io1990thrrc9cvxhjmsmx5pysznqs734h6uhxfxkq"
        token2: "0x0b3F868E0BE5597D5DB7fEB59E1CADBb0fdDa50a"
      # QUICK
      - token1: "io1u346nz58mj5cjuj7ng3cn96upwam37v9axtju2"
        token2: "0x831753DD7087CaC61aB5644b308642cc1c33Dc13"
      # AAVE
      - token1: "io14tw8gyn3p8v5fcmvh4c0w8797ryjrlrvnsr6zf"
        token2: "0xD6DF932A45C0f255f85145f286eA0b292B21C90B"
      # CYC
      - token1: "io1f4acssp65t6s90egjkzpvrdsrjjyysnvxgqjrh"
        token2: "0xcFb54a6D2dA14ABeCD231174FC5735B4436965D8"
      # CIOTX
      - token1: "io1nxetpma4de3wx6tqcgxdtj5wc64a24t64dc76s"
        token2: "0x300211Def2a644b036A9bdd3e58159bb2074d388"
      # SHIBX
      - token1: "io1g29kuat5d727cqcjv5ta8607ys9kdp5fx702ua"
        token2: "0xe04E81331bDcBfBF2D1342714812d546a55CB6DC"
      # GEOD
      - token1: "io13cej9ysx7unfj0j200ma5g687d6rh795rk3v3n"
        token2: "0xf53224ec685b674eb4f5c365d30876efb05fbfe5"
      # DIMO
      - token1: "io1v8dekzzrymfz28xtqffvrr7ekr5g0jj0fcz5ea"
        token2: "0x7c09a86b761bfd9d996fe0d7ff8390c4ee7b3aec"
      # XNET
      - token1: "io12t04n0staz4a4wafuwrzerq0r79nl6w2cphpeh"
        token2: "0x1524b9de9aa259633a2e1dad37476f24898e3aaa"
      # WNT
      - token1: "io12falqd0u5fje0jtx23n535egfzkl2gtwes6r58"
        token2: "0xFBcAA472E25994E96889ae33C1b185DaD7bFf3Ef"
      # WIFI
      - token1: "io1em553udth5j85hjp4z9j3xgdhq00qz7uq5egha"
        token2: "0x8F26b442B6681567f6EaA75828140712f939Fb9e"
      # DATA
      - token1: "io1rt3y6jfg4ph64txhrn6pf54n5jv6mv5mjlp37u"
        token2: "0x72F30B99C6bc3681508950b47A50fe0b18eF4BE6"
      # MYST
      - token1: "io1t6ujp39vhku3adg3uxajjvcgyu5h36q8yfsurk"
        token2: "0x9D06d28aDaC1d9843034c61EE22991469413d790"
