chain: "bsc"
grpcPort: 9286
grpcProxyPort: 9287
interval: 30s
batchSize: 100
database:
  uri: "root:kdfjjrU64fjK58H@tcp(localhost:13306)/witness?parseTime=true"
  driver: "mysql"
cashiers:
  - id: "bsc-to-iotex-payload"
    withPayload: true
    relayerURL: ":7201"
    startBlockHeight: 43283329
    cashierContractAddress: "0x78de1E0b76523Ac6E190F89FFC46571346940204"
    tokenSafeContractAddress: "0xfbe9a4138afdf1fa639a8c2818a0c4513fc4ce4b"
    validatorContractAddress: "0x915241176a644A29F46F5F4F8Bd49309e461a9bD"
    transferTableName: "bsc_transfers"
    tokenPairs:
      - token1: "0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c"
        token2: "io1jlnvfzr8lhper2xla8gknmxsqhgajq5ravu4wr"
      - token1: "0xe9e7cea3dedca5984780bafc599bd69add087d56"
        token2: "io1sj4uk2pjhesxxsd9qy52avwmgw4qzazfrypm04"
      - token1: "0x810ee35443639348adbbc467b33310d2ab43c168"
        token2: "io1f4acssp65t6s90egjkzpvrdsrjjyysnvxgqjrh"
      - token1: "0x2aaF50869739e317AB80A57Bf87cAA35F5b60598"
        token2: "io1nxetpma4de3wx6tqcgxdtj5wc64a24t64dc76s"
      - token1: "0x55d398326f99059ff775485246999027b3197955"
        token2: "io1gtyj2h272ghg8vtw5ydrhgzv95a0egre4zemtf"
      - token1: "0x8ac76a51cc950d9822d68b83fe1ad97b32cd580d"
        token2: "io1qde5ded9wg540tpv4dkwhrr5lsvva2ga3hf6ry"
      - token1: "0x7e544f2fEDDc69b1cB12555779c824CFe100ee34"
        token2: "io1p00c9unkxz0zal2fglhguz3y3vnjd6xlx24h8m"
      - token1: "0x049Dd7532148826CdE956c7B45fec8c30b514052"
        token2: "io19zrne65vymmq8v2exluesk5g33w6tlvskfj3c9"
      - token1: "0xa0CB9c8e470EC591dd7f5De650af9468EE6f7d5A"
        token2: "io1cx6cvg9dswfc83nzhl5qmdz3gdzda3khtt6asw"
      # THC
      - token1: "0x8Dfb1099C53f634BEcf3C98aE19eB1BAA1b37D43"
        token2: "io1kn9axz8g08qv8gafj6kkcatkky362ph5jntc9r"
      # IoTexShiba
      - token1: "0x52702a7301be185cc97bf3fe6d497a83e7772fde"
        token2: "io1ld5l9sxecjzkftkn9tcudu6z5qmvjj2zfamvcw"
      # DRF
      - token2: "io1mm5eya89mz3dmp0lqtlfuydf67nrdhnwg92dy4"
        token1: "0x02dF5253Bc4EfC9F8f744133Ff99981b18Df0473"
