chain: "matic"
grpcPort: 9284
grpcProxyPort: 9285
interval: 20s
batchSize: 100
confirmBlockNumber: 255
database:
  uri: "root:kdfjjrU64fjK58H@tcp(localhost:13306)/witness?parseTime=true"
  driver: "mysql"
cashiers:
  - id: "matic-to-iotex-payload"
    withPayload: true
    relayerURL: ":7201"
    startBlockHeight: 63196610
    cashierContractAddress: "0x990B503f8C7353f1caB6f9D5bbF8f0Be2718D731"
    tokenSafeContractAddress: "0xA239F03Cda98A7d2AaAA51e7bF408e5d73399e45"
    validatorContractAddress: "0x915241176a644A29F46F5F4F8Bd49309e461a9bD"
    transferTableName: "matic_transfers"
    tokenPairs:
      - token2: "io13envp44hps9j85ulfvs6r6k99wagaky60pzl2c"
        token1: "0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270"
      - token2: "io1v5m9d7zrs852xkdzdresqf3phwc5cchc5crylc"
        token1: "0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619"
      - token2: "io10u9dv0ys93nmr7smzyptpkhlhzylt4wtqzrvld"
        token1: "0x1BFD67037B42Cf73acF2047067bd4F2C47D9BfD6"
      - token2: "io1v25anp7t7nz954gdam2m27eqp4arr93jly4maa"
        token1: "0x8f3Cf7ad23Cd3CaDbD9735AFf958023239c6A063"
      - token2: "io18ndhcj88pwz5a5h68yhzz6r4q8vykwhugq45ns"
        token1: "0xc2132D05D31c914a87C6611C10748AEb04B58e8F"
      - token2: "io1cpx682vazuf4s4amjd7jlwejr5akc65plgmdru"
        token1: "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174"
      - token2: "io1990thrrc9cvxhjmsmx5pysznqs734h6uhxfxkq"
        token1: "0x0b3F868E0BE5597D5DB7fEB59E1CADBb0fdDa50a"
      - token2: "io1u346nz58mj5cjuj7ng3cn96upwam37v9axtju2"
        token1: "0x831753DD7087CaC61aB5644b308642cc1c33Dc13"
      - token2: "io14tw8gyn3p8v5fcmvh4c0w8797ryjrlrvnsr6zf"
        token1: "0xD6DF932A45C0f255f85145f286eA0b292B21C90B"
      - token2: "io1f4acssp65t6s90egjkzpvrdsrjjyysnvxgqjrh"
        token1: "0xcFb54a6D2dA14ABeCD231174FC5735B4436965D8"
      - token2: "io1nxetpma4de3wx6tqcgxdtj5wc64a24t64dc76s"
        token1: "0x300211Def2a644b036A9bdd3e58159bb2074d388"
      - token2: "io1g29kuat5d727cqcjv5ta8607ys9kdp5fx702ua"
        token1: "0xe04E81331bDcBfBF2D1342714812d546a55CB6DC"
      # GEOD
      - token2: "io13cej9ysx7unfj0j200ma5g687d6rh795rk3v3n"
        token1: "0xf53224ec685b674eb4f5c365d30876efb05fbfe5"
      # DIMO
      - token2: "io1v8dekzzrymfz28xtqffvrr7ekr5g0jj0fcz5ea"
        token1: "0x7c09a86b761bfd9d996fe0d7ff8390c4ee7b3aec"
      # XNET
      - token2: "io12t04n0staz4a4wafuwrzerq0r79nl6w2cphpeh"
        token1: "0x1524b9de9aa259633a2e1dad37476f24898e3aaa"
      # WNT
      - token2: "io12falqd0u5fje0jtx23n535egfzkl2gtwes6r58"
        token1: "0xFBcAA472E25994E96889ae33C1b185DaD7bFf3Ef"
      # WIFI
      - token2: "io1em553udth5j85hjp4z9j3xgdhq00qz7uq5egha"
        token1: "0x8F26b442B6681567f6EaA75828140712f939Fb9e"
      # DATA
      - token2: "io1rt3y6jfg4ph64txhrn6pf54n5jv6mv5mjlp37u"
        token1: "0x72F30B99C6bc3681508950b47A50fe0b18eF4BE6"
      # MYST
      - token2: "io1t6ujp39vhku3adg3uxajjvcgyu5h36q8yfsurk"
        token1: "0x9D06d28aDaC1d9843034c61EE22991469413d790"
