chain: "iotex"
grpcPort: 9320
grpcProxyPort: 9321
interval: 30s
batchSize: 1000
database:
  uri: "root:kdfjjrU64fjK58H@tcp(localhost:13306)/witness?parseTime=true"
  driver: "mysql"
cashiers:
  - id: "iotex-to-solana"
    relayerURL: ":7007"
    startBlockHeight: 31936000
    validatorContractAddress: "7yDLTWW6DXf1UW87TkKusELA7N7xfq9bhRe3WRHCHHDK"
    tokenSafeContractAddress: "0x127A3aC5F19833D2CCA091231DCf550213Fe4Fac"
    cashierContractAddress: "0x1c80507d92a86699f63737220247788d0a4bfd11"
    transferTableName: "iotex_to_solana_transfers"
    tokenPairs:
      # WSOL
      - token1: "io158elyywekvljpp4gqzzzsdkk0ufehxn6g3aa0u"
        token2: "3qdPWqm2iEYkTXRk3XGkuabEeXfentCUwJP1cCWrkre5"
        tokenMint: "So11111111111111111111111111111111111111112"
      # CIOTX
      - token1: "io1nxetpma4de3wx6tqcgxdtj5wc64a24t64dc76s"
        token2: "8DqC4xipdSztGiTmVRPoAYbfa4hKmTDvPMzmfCUxmU8S"
        tokenMint: "xgf3DoXeqCRVJ9hzU2vbTjfbs6j5BpCHWSmVGBV7Ryx"
      # RENDER
      - token1: "io12pmu2xkcyk97w2ykk53fs76fq6x6yv43wccrvg"
        token2: "AhncMbaGvpmb9tFSfQ71fBba5mLHQvXvmRwvijUir2tH"
        tokenMint: "rndrizKT3MK1iimdxRdWabcF7Zg7AR5T4nud4EkHBof"
      # HNT
      - token1: "io1gpssx9dzxw6w7zfzukj0ds582uxl3gzh9zuxgm"
        token2: "Dh1gzxoMcFFXeeWR3ZXcwHwC2eNU95trRZg1LdZTYn99"
        tokenMint: "hntyVP6YFm1Hg25TN9WGLqM12b8TQmcknKrdu1oxWux"
      # HONEY
      - token1: "io1y6xzvfh33qkwxmc9qe4f7t0us90f25kfx4t8jy"
        token2: "7hkt6RgQPx2PqqWVf7KFujZCaFfm7EA5QRrDavuGtGTi"
        tokenMint: "4vMsoUT2BWatFweudnQM1xedRLfJgJ7hswhcpz4xgBTy"
      # IO
      - token1: "io1dzxds9fqwnv4jjznx0e2j97pfp9lgcp837dqfk"
        token2: "148xknhJQwpUnZKbnACA1fbpToCzJBwM5nxzs1AhasDh"
        tokenMint: "BZLbGTNCSFfoth2GYDtwr7e4imWzpR5jqcUuGEwr646K"
      # NATIX
      - token1: "io1sw3wjtcpkvv35pem49qtr58y47nl4rxu7nt77j"
        token2: "8jpZHZ14vfarAKnrzgx8bZX8tSgATB7msiswS2g1MAk2"
        tokenMint: "FRySi8LPkuByB7VPSCCggxpewFUeeJiwEGRKKuhwpKcX"
      # UPT
      - token1: "io104h9nyp4f2yeu08ra6927hecphw3k2dpyrnt5j"
        token2: "2TANKzurze7DLzGs1b5QEurgTEiKm8crBhiPMdFxHxCE"
        tokenMint: "UPTx1d24aBWuRgwxVnFmX4gNraj3QGFzL3QqBgxtWQG"
    decimalRound:
      - token1: "io1nxetpma4de3wx6tqcgxdtj5wc64a24t64dc76s"
        amount: -9
    toSolana: true