chain: "solana"
grpcPort: 9120
grpcProxyPort: 9121
interval: 1m
batchSize: 150
database:
  uri: "root:kdfjjrU64fjK58H@tcp(localhost:13306)/witness?parseTime=true"
  driver: "mysql"
cashiers:
  - id: "solana-to-iotex"
    relayerURL: ":7008"
    startBlockHeight: 287672853
    validatorContractAddress: "io1tv0xfyh5ky8ntpf8kxwcs4r37nzfp27k5pu07k"
    cashierContractAddress: "A9SGRcytnfx6U1QrnMUwK5sxYyCYY3MpyrPcyeafhSMF"
    transferTableName: "solana_to_iotex_transfers"
    qpsLimit: 5
    disablePull: true
    tokenPairs:
      # WSOL
      - token1: "So11111111111111111111111111111111111111112"
        token2: "0xA1F3f211d9B33f2086a800842836D67F139B9A7A"
      # CIOTX
      - token1: "xgf3DoXeqCRVJ9hzU2vbTjfbs6j5BpCHWSmVGBV7Ryx"
        token2: "0x99b2b0efb56e62e36960c20cd5ca8ec6abd5557a"
      # RENDER
      - token1: "rndrizKT3MK1iimdxRdWabcF7Zg7AR5T4nud4EkHBof"
        token2: "0x5077C51aD8258bE72896B522987b49068da232B1"
      # HNT
      - token1: "hntyVP6YFm1Hg25TN9WGLqM12b8TQmcknKrdu1oxWux"
        token2: "0x40610315A233b4ef0922E5A4f6C287570dF8a057"
      # HONEY
      - token1: "4vMsoUT2BWatFweudnQM1xedRLfJgJ7hswhcpz4xgBTy"
        token2: "0x268c2626f1882cE36F05066a9f2dFC815e9552C9"
      # IO
      - token1: "BZLbGTNCSFfoth2GYDtwr7e4imWzpR5jqcUuGEwr646K"
        token2: "0x688Cd8152074D959485333f2A917c1484Bf46027"
      # NATIX
      - token1: "FRySi8LPkuByB7VPSCCggxpewFUeeJiwEGRKKuhwpKcX"
        token2: "0x83A2e92f01b3191a073bA940B1d0e4Afa7fA8CDC"
      # UPT
      - token1: "UPTx1d24aBWuRgwxVnFmX4gNraj3QGFzL3QqBgxtWQG"
        token2: "0x7D6e5990354a899e3cE3Ee8aAF5f380dDD1b29A1"
    decimalRound:
      - token1: "xgf3DoXeqCRVJ9hzU2vbTjfbs6j5BpCHWSmVGBV7Ryx"
        amount: 9